server:
  port: 8204
spring:
  application:
    name: gateway-server
  cloud:
    consul:
      host: 172.17.0.1 #注册源
      port: 8500 #注册端口
      discovery:
        service-name: ${spring.application.name} #注册到Consul的服务名称
        health-check-url: http://172.17.0.1:8204/actuator/health
        hostname: 172.17.0.1

  boot:
    admin:
      client:
        url: "http://172.17.0.1:8205"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


zuul:
  sensitive-headers: #敏感头部，设置为空，防止截获Authorization
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

#遵循默认路由规则：http://ZUUL_HOST:ZUUL_PORT/微服务注册中心serviceId/**



