
server:
  port: 8211 #应用端口
spring:
  application:
    name: hcnet-website #应用名
  cloud:
    consul: #服务发现
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        enabled: true
  servlet: #上传配置
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1000MB
      max-request-size: 1000MB
      resolve-lazily: false
  datasource: #数据库配置
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///hc_official_website_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      filters: stat, wall, config
      initial-size: 1
      max-active: 100
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        wall:
          config:
            multi-statement-allow: true #允许一次批量更新操作，会导致SQL注入
#  mvc: #直接定义过滤规则与静态资源位置
#    static-path-pattern: /static/**
#  resources:
#    static-locations: classpath:/static/
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false


#  rabbitmq: #消息中间件
#    host: 47.97.170.173
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
management: #暴露健康状况
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
mybatis: #Mybaytis映射文件位置
  mapper-locations: classpath:/mappers/*Mapper.xml
  configuration:
    aggressive-lazy-loading: false #当参数设置为false时，对任意延迟属性的调用都将按需加载
#feign: #开启熔断
feign:
  hystrix:
    enabled: true
