version: '3'
services:
  micro-gateway-server:
    image: 172.18.0.1:5000/gateway-server:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
    - 8204:8204
  micro-config-server:
    image: 172.18.0.1:5000/config-server:0.0.1-SNAPSHOT
    ports:
    - 8200:8200
    restart: on-failure
  micro-admin-server:
    image: 172.18.0.1:5000/admin-server:0.0.1-SNAPSHOT
    ports:
    - 8205:8205
    restart: on-failure
  micro-log-server:
    image: 172.18.0.1:5000/log-server:0.0.1-SNAPSHOT
    ports:
    - 8206:8206
  micro-monitoring-server:
    image: 172.18.0.1:5000/monitoring-server:0.0.1-SNAPSHOT
    ports:
    - 8202:8202
    restart: on-failure
  micro-micro-consumer:
    image: 172.18.0.1:5000/micro-consumer:0.0.1-SNAPSHOT
    ports:
    - 8209:8209
    restart: on-failure
  micro-micro-consumer-1:
    image: 172.18.0.1:5000/micro-consumer-1:0.0.1-SNAPSHOT
    ports:
      - 8213:8213
    restart: on-failure
  micro-uaa-server:
    image: 172.18.0.1:5000/uaa-server:0.0.1-SNAPSHOT
    ports:
      - 8203:8203
    restart: on-failure
  micro-user-service:
    image: 172.16.199.25:5000/user-service:0.0.1-SNAPSHOT
    ports:
    - 8201:8201
    restart: on-failure
  micro-upload-apk:
    image: 172.18.0.1:5000/upload-apk:0.0.1-SNAPSHOT
    ports:
      - 8207:8207
    restart: on-failure
  micro-hcnet-website-1:
    image: 172.18.0.1:5000/hcnet-website-12:0.0.1-SNAPSHOT
    ports:
    - 8211:8211
    restart: on-failure