#version: '3'
#services:
#  mysql:
#    image: mysql
#    restart: on-failure
#    ports:
#    - 3306:3306
#    volumes:
#    - microservice-net
#    networks:
#      -microservice-net:
#
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: hc_file_upload_apk_ldy
#  upload-apk:
#    image:
#    restart: on-failure
#    ports:
#    - 8207:8207
#    networks:
#      -microservice-net:
#
#
#networks:
#  microservice-net:
#volumes:
#  microservice-mysql:
#version: '3'
#services:
#  config-server:
#    build: ./config-server
#    ports:
#      - "8200:8200"
#    links:
#      - admin-server
#    admin-server:
#    build: ./admin-server
#    ports:
#      - "8205:8205"
version: 3
services:
  logstash:
    image: logstash:5.4.0
    volumes:
    - ~/Document/logstash/logstash.conf:/etc/logstash.conf
    ports:
    - "5000:5000/tcp"
    - "5000:5000/udp"
    links:
      - elasticsearch
    command:
      -f /etc/logstash.conf
  elasticsearch:
    image: elasticsearch:5.4.0
  kibana:
    image: kibana:5.4.0
    links:
      - elasticsearch
    ports:
      - "5601:5601"
