server:
  port: 8206
spring:
  application:
    name: log-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  boot:
    admin:
      client:
        url: "http://localhost:8205"
        instance:
          service-base-url: "http://localhost:8205"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: / #默认根目录
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: druidDataSource
    druid:

      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.97.170.173:3306/lidengyin_mango?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
      filters: stat, wall, config
      initial-size: 1
      max-active: 100
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
