server:
  port: 8207
spring:
  application:
    name: upload-apk
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100000000
      max-request-size: 100000000
      resolve-lazily: false
  boot:
    admin:
      client:
        url: "http://172.17.0.1:8205"
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.17.0.1:3306/hc_file_upload_apk_ldy?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      filters: stat, wall, config
      initial-size: 1
      max-active: 100
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

      username: root
      password: 123456
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    publisher-confirms: true
    virtual-host: /
    host: 172.17.0.1

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
feign:
  hystrix:
    enabled: true
